export const environment = {
  APPWRITE_API_ENDPOINT: '',
  APPWRITE_PROJECT_ID: '',
  APPWRITE_DB_ID: '',
  MESSAGES_COLLECTION_ID: '',
  BUGS_COLLECTION_ID: '',
  NEW_TOOL_REQUESTS_COLLECTION_ID: ''
};
