'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const { buildEnvironmentFileContent, REQUIRED_KEYS } = require('./generate-environment');

test('buildEnvironmentFileContent', async (t) => {
  await t.test('writes every value when all required keys are present', () => {
    const env = {
      APPWRITE_API_ENDPOINT: 'https://cloud.appwrite.io/v1',
      APPWRITE_PROJECT_ID: 'project-id',
      APPWRITE_DB_ID: 'db-id',
      MESSAGES_COLLECTION_ID: 'messages-id',
      BUGS_COLLECTION_ID: 'bugs-id',
      NEW_TOOL_REQUESTS_COLLECTION_ID: 'requests-id',
    };

    const content = buildEnvironmentFileContent(env, REQUIRED_KEYS);

    assert.equal(
      content,
      '// This file is generated by scripts/generate-environment.js from .env — do not edit directly.\n' +
        'export const environment = {\n' +
        '  APPWRITE_API_ENDPOINT: "https://cloud.appwrite.io/v1",\n' +
        '  APPWRITE_PROJECT_ID: "project-id",\n' +
        '  APPWRITE_DB_ID: "db-id",\n' +
        '  MESSAGES_COLLECTION_ID: "messages-id",\n' +
        '  BUGS_COLLECTION_ID: "bugs-id",\n' +
        '  NEW_TOOL_REQUESTS_COLLECTION_ID: "requests-id"\n' +
        '};\n'
    );
  });

  await t.test('warns and falls back to an empty string for missing keys', (t) => {
    const warnCalls = [];
    t.mock.method(console, 'warn', (...args) => warnCalls.push(args.join(' ')));

    const content = buildEnvironmentFileContent({ APPWRITE_API_ENDPOINT: 'https://cloud.appwrite.io/v1' }, [
      'APPWRITE_API_ENDPOINT',
      'APPWRITE_PROJECT_ID',
    ]);

    assert.equal(warnCalls.length, 1);
    assert.match(warnCalls[0], /Missing \.env value\(s\): APPWRITE_PROJECT_ID/);
    assert.match(content, /APPWRITE_API_ENDPOINT: "https:\/\/cloud\.appwrite\.io\/v1"/);
    assert.match(content, /APPWRITE_PROJECT_ID: ""/);
  });

  await t.test('does not warn when every key is present', (t) => {
    const warnCalls = [];
    t.mock.method(console, 'warn', (...args) => warnCalls.push(args.join(' ')));

    buildEnvironmentFileContent({ APPWRITE_API_ENDPOINT: 'value' }, ['APPWRITE_API_ENDPOINT']);

    assert.equal(warnCalls.length, 0);
  });

  await t.test('safely escapes values containing quotes and backslashes', () => {
    const content = buildEnvironmentFileContent({ APPWRITE_API_ENDPOINT: 'a "quoted" value \\ here' }, [
      'APPWRITE_API_ENDPOINT',
    ]);

    assert.match(content, /APPWRITE_API_ENDPOINT: "a \\"quoted\\" value \\\\ here"/);
    // The generated value must parse back to the exact original string.
    const parsed = JSON.parse(content.match(/APPWRITE_API_ENDPOINT: (".*")/)[1]);
    assert.equal(parsed, 'a "quoted" value \\ here');
  });
});
