export enum ApplicationConfig {
  TYPING_TIMEOUT = 1000,
  MIN_ROUND_DIGITS = 0,
  DEFAULT_ROUND_DIGITS = 2,
  MAX_ROUND_DIGITS = 15,
  MAX_FORM_INPUT_LENGTH = 40,
  MAX_FORM_TEXTAREA_LENGTH = 1000,
}

export enum LayoutConfig {
  ROW_GUTTER = 15,
}
